
import { Recipe } from './types';

export const recipes: Recipe[] = [
  {
    id: 'palov',
    name: "O'zbek Palovi (Osh)",
    category: 'Asosiy',
    difficulty: 'Bayramona',
    prepTime: '40 min',
    cookTime: '90 min',
    servings: 6,
    price: 45000,
    estimatedDelivery: '35-50 min',
    metaTitle: "Haqiqiy O'zbek Palovi Retsepti | Och Qolma",
    metaDescription: "Eng mazali o'zbek palovini tayyorlash sirlari. 1kg guruch va go'sht nisbatida mukammal osh tayyorlang. Oshpaz tavsiyalari.",
    description: "O'zbek dasturxonining shohi. Go'sht, guruch va sabzining oltin nisbati.",
    history: "Palov (Osh-i-palov) - nomi 7 ta masalliq bosh harfidan olingan: Piyoz, Ayoz (sabzi), Lahm (go'sht), Oliy (yog'), Vejet (tuz), Ob (suv), Lola (guruch). Ibn Sino uni darmon sifatida yozgan.",
    ingredients: ["1kg Lazer guruchi", "1kg Qo'y go'shti", "1kg Sabzi", "300ml Yog'", "Piyoz", "Zira", "Tuz"],
    steps: ["Go'shtni qovuring", "Piyoz va sabzi soling", "Zirvak qaynating", "Guruch solib suvini chektiring", "25 daqiqa dam bering"],
    secrets: ["Sabzini faqat qo'lda to'g'rang", "Guruchni iliq tuzli suvda yuvish shart", "Zira sifatli bo'lishi kerak"],
    serving: "Katta laganda, achchiq-chuchuk salati bilan.",
    seoKeywords: ["palov retsepti", "o'zbek palovi", "osh tayyorlash", "milliy osh", "palov sirlari"],
    image: "https://images.unsplash.com/photo-1512058560366-cd2427ff667f?auto=format&fit=crop&q=80&w=800"
  },
  {
    id: 'lagmon',
    name: "Cho'zma Lag'mon",
    category: 'Asosiy',
    difficulty: "An'anaviy",
    prepTime: '60 min',
    cookTime: '40 min',
    servings: 4,
    price: 32000,
    estimatedDelivery: '40-60 min',
    metaTitle: "Lag'mon Retsepti va Tayyorlash | Och Qolma",
    metaDescription: "Qo'lda cho'zilgan xamir va sershira waja. Haqiqiy o'zbek lag'monini uyingizda pishiring.",
    description: "Uzun xamir va sershira sabzavotli qayla (waja) uyg'unligi.",
    history: "Ipak Yo'li bo'ylab savdogarlar orqali kirib kelgan va milliy ruh bilan boyitilgan taom.",
    ingredients: ["500g Un", "1 dona Tuxum", "400g Mol go'shti", "Turp", "Bulg'or qalampiri", "Pomidor", "Sarimsoq"],
    steps: ["Xamir qoring va pishiting", "Ingichka qilib cho'zing", "Suvda pishirib oling", "Waja (qayla) tayyorlang", "Xamir ustiga quyib torting"],
    secrets: ["Xamirni tindirish cho'zilish siri", "Wajani baland olovda qovuring"],
    serving: "Chuqur kosada, ko'katlar va lazzat bilan.",
    seoKeywords: ["lag'mon retsepti", "cho'zma lag'mon", "waja tayyorlash", "lag'mon sirlari"],
    image: "https://images.unsplash.com/photo-1585032226651-759b368d7246?auto=format&fit=crop&q=80&w=800"
  },
  {
    id: 'manti',
    name: "Sershira Manti",
    category: 'Xamir',
    difficulty: "An'anaviy",
    prepTime: '45 min',
    cookTime: '45 min',
    servings: 5,
    price: 38000,
    estimatedDelivery: '45-60 min',
    metaTitle: "Manti Tayyorlash va Qiyma Sirlari | Och Qolma",
    metaDescription: "Bug'da pishiriladigan sershira manti. Yupqa xamir va go'shtli qiyma nisbati.",
    description: "Yupqa xamir ichiga yashiringan sershira go'sht va piyoz lazzati.",
    history: "Markaziy Osiyo xalqlarining eng sevimli va to'yimli bug'da pishadigan taomi.",
    ingredients: ["600g Un", "500g Qiyma", "500g Piyoz", "Dumba yog'i", "Zira", "Murch"],
    steps: ["Xamir qoring", "Piyoz va go'shtni to'g'rang", "Yupqa yoyib tuging", "45 daqiqa bug'da pishiring"],
    secrets: ["Piyoz qancha ko'p bo'lsa manti shuncha shira beradi", "Qasqonni yog'lashni unutmang"],
    serving: "Sariyog' va qatiq bilan.",
    seoKeywords: ["manti tayyorlash", "o'zbek mantisi", "manti retsepti", "bug'da pishgan ovqatlar"],
    image: "https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?auto=format&fit=crop&q=80&w=800"
  },
  {
    id: 'somsa',
    name: "Varaqi Somsa",
    category: 'Xamir',
    difficulty: "An'anaviy",
    prepTime: '90 min',
    cookTime: '35 min',
    servings: 10,
    price: 8000,
    estimatedDelivery: '30-45 min',
    metaTitle: "Somsa Qanday Qilinadi? Varaqi Somsa | Och Qolma",
    metaDescription: "Qatlama xamir va sershira qiyma. Somsa pishirishning barcha sirlari va usullari.",
    description: "Og'izda eriydigan qarsildoq qatlamlar va sershira go'sht.",
    history: "Qadimda karvon yo'llari bo'ylab sayyohlarning eng sevimli yo'l ozuqasi bo'lgan.",
    ingredients: ["1kg Un", "250g Sariyog'", "700g Go'sht", "Piyoz", "Sedana"],
    steps: ["Varaqi xamir tayyorlang", "Xamirni tindiring", "Qiyma solib tuging", "Duxovkada 200 gradusda pishiring"],
    secrets: ["Sariyog'ni sovuq surting", "Piyozni qo'lda to'g'rang"],
    serving: "Pomidorli sous va issiq choy bilan.",
    seoKeywords: ["somsa qanday qilinadi", "qatlama somsa", "somsa retsepti", "varaqi somsa"],
    image: "https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&q=80&w=800"
  },
  {
    id: 'shashlik',
    name: "G'ijduvon Kabobi",
    category: 'Kabob',
    difficulty: 'Tez',
    prepTime: '120 min',
    cookTime: '15 min',
    servings: 4,
    price: 18000,
    estimatedDelivery: '30-45 min',
    metaTitle: "Shashlik Marinovka Sirlari | Och Qolma",
    metaDescription: "Go'shtni yumshoq marinovka qilish. Eng yaxshi o'zbek shashlik retseptlari.",
    description: "Ko'mir taftida pishgan xushbo'y va sershira go'sht bo'laklari.",
    history: "Buxoro vohasining eng mashhur va qadimiy kabob pishirish uslubi.",
    ingredients: ["1kg Qo'y go'shti", "Piyoz", "Mineral suv", "Zira", "Kashnich urug'i"],
    steps: ["Go'shtni bo'laklang", "Marinovka qiling", "Sixga tizing", "Ko'mirda pishiring"],
    secrets: ["Gazli suv go'shtni yumshatadi", "Ko'mir tafti o'rtacha bo'lishi kerak"],
    serving: "To'g'ralgan piyoz va uksus bilan.",
    seoKeywords: ["shashlik retsepti", "kabob marinovka", "o'zbek shashligi", "kabob sirlari"],
    image: "https://images.unsplash.com/photo-1635773103713-398d5c953531?auto=format&fit=crop&q=80&w=800"
  },
  {
    id: 'norin',
    name: "Norin Osh",
    category: 'Xamir',
    difficulty: 'Bayramona',
    prepTime: '180 min',
    cookTime: '60 min',
    servings: 8,
    price: 40000,
    estimatedDelivery: '45-70 min',
    metaTitle: "Norin Osh Tayyorlash | Och Qolma",
    metaDescription: "Qazili norin retsepti. Xamirni quritish va kesish sirlari. Toshkent norini.",
    description: "Yupqa kesilgan xamir va sur go'shtning shohona uyg'unligi.",
    history: "Toshkent shahrining eng nufuzli va bayramona milliy taomi.",
    ingredients: ["1kg Un", "1kg Mol go'shti", "Qazi", "Murch", "Yog'"],
    steps: ["Go'shtni qaynatib pishiring", "Xamirni pishirib quriting", "Ingichka kesing", "Murch bilan aralashtiring"],
    secrets: ["Xamir va go'sht juda ingichka kesilishi shart", "Sho'rvani alohida bering"],
    serving: "Sovuq holda, issiq sho'rva bilan.",
    seoKeywords: ["norin osh", "norin retsepti", "toshkent norini", "qazili norin"],
    image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&q=80&w=800"
  },
  {
    id: 'chuchvara',
    name: "Mayda Chuchvara",
    category: 'Suyuq',
    difficulty: 'Tez',
    prepTime: '40 min',
    cookTime: '20 min',
    servings: 4,
    price: 28000,
    estimatedDelivery: '30-45 min',
    metaTitle: "Chuchvara Retsepti | Och Qolma",
    metaDescription: "Mayda chuchvara tugish va pishirish. Uy sharoitida mazali suyuq taom.",
    description: "Mittigina tugilgan xamirchalar, sershira sho'rva bilan.",
    history: "Oila a'zolari yig'ilib birgalikda tayyorlaydigan birdamlik taomi.",
    ingredients: ["500g Un", "400g Qiyma", "Piyoz", "Ko'katlar", "Qaymoq"],
    steps: ["Xamirni yoyib kesing", "Mittigina qilib tuging", "Sho'rvada pishiring", "Qaymoq bilan torting"],
    secrets: ["Chuchvara qancha mayda bo'lsa shuncha mahoratli sanalasiz", "Rayhon qo'shing"],
    serving: "Kosa bilan, ko'katlar sepib.",
    seoKeywords: ["chuchvara retsepti", "mayda chuchvara", "o'zbek barak", "suyuq ovqatlar"],
    image: "https://images.unsplash.com/photo-1547592110-823d6330005d?auto=format&fit=crop&q=80&w=800"
  },
  {
    id: 'qovurma',
    name: "Qovurma Lag'mon",
    category: 'Asosiy',
    difficulty: 'Tez',
    prepTime: '30 min',
    cookTime: '25 min',
    servings: 2,
    price: 35000,
    estimatedDelivery: '35-50 min',
    metaTitle: "Qovurma Lag'mon Retsepti | Och Qolma",
    metaDescription: "Go'sht va sabzavotlar bilan qovurilgan lag'mon. Tez va to'yimli tushlik.",
    description: "Jizillab qovurilgan go'sht va xamirning quruq variantdagi uyg'unligi.",
    history: "Baland olovda tez tayyorlanadigan eng to'yimli milliy taomlardan biri.",
    ingredients: ["500g Lag'mon xamiri", "300g Go'sht", "Sabzi", "Piyoz", "Kashnich"],
    steps: ["Go'shtni qovuring", "Sabzavotlarni soling", "Xamirni qo'shing", "Ziravorlar bilan qovurib oling"],
    secrets: ["Sarimsoqni oxirida qo'shing", "Sabzavotlar o'lib ketmasligi kerak"],
    serving: "Yassi laganda, ustiga tuxum qovurib qo'yilishi mumkin.",
    seoKeywords: ["qovurma lag'mon", "qovurma retsepti", "milliy qovurma", "tezkor tushlik"],
    image: "https://images.unsplash.com/photo-1603048588665-791ca8aea617?auto=format&fit=crop&q=80&w=800"
  }
];
