
import { Recipe } from './types';

export const recipes: Recipe[] = [
  {
    id: 'palov',
    name: "O'zbek Palovi (Osh)",
    category: 'Asosiy',
    difficulty: 'Bayramona',
    prepTime: '40 min',
    cookTime: '90 min',
    servings: 6,
    price: 45000,
    estimatedDelivery: '35-50 min',
    metaTitle: "Haqiqiy O'zbek Palovi Retsepti | Och Qolma",
    metaDescription: "Eng mazali o'zbek palovini tayyorlash sirlari. 1kg guruch va go'sht nisbatida mukammal osh tayyorlang. Professional oshpaz tavsiyalari.",
    description: "O'zbek dasturxonining shohi. Go'sht, guruch va sabzining mukammal uyg'unligi.",
    history: "Palov (Osh-i-palov) - nomi 7 ta masalliq bosh harfidan olingan: Piyoz, Ayoz (sabzi), Lahm (go'sht), Oliy (yog'), Vejet (tuz), Ob (suv), Lola (guruch). Abu Ali ibn Sino uni shifobaxsh dori sifatida tavsiya qilgan.",
    ingredients: ["1000g Lazer guruchi", "1000g Qo'y go'shti", "1000g Sabzi (sariq/qizil)", "300ml Paxta yog'i", "200g Piyoz", "50g Zira", "Tuz"],
    steps: ["Yog'ni qizdirib go'shtni qovuring", "Piyoz va sabzi solib zirvak tayyorlang", "Suv quyib 50 min qaynating", "Guruchni solib baland olovda suvini chektiring", "25 min dam bering"],
    secrets: ["Sabzini faqat qo'lda to'g'rang", "Guruchni iliq tuzli suvda yuvish shart", "Zirva pishganda tuzini ko'ring"],
    serving: "Katta laganda, ustiga qazi va go'shtlar to'g'ralgan holda.",
    seoKeywords: ["palov retsepti", "o'zbek palovi", "osh tayyorlash", "milliy osh", "to'y palovi"],
    image: "https://images.unsplash.com/photo-1512058560366-cd2427ff667f?auto=format&fit=crop&q=80&w=800"
  },
  {
    id: 'lagmon',
    name: "Cho'zma Lag'mon",
    category: 'Asosiy',
    difficulty: "An'anaviy",
    prepTime: '60 min',
    cookTime: '40 min',
    servings: 4,
    price: 32000,
    estimatedDelivery: '40-60 min',
    metaTitle: "Lag'mon Retsepti va Tayyorlash | Och Qolma",
    metaDescription: "Qo'lda cho'zilgan xamir va sershira waja. Haqiqiy o'zbek/uyg'ur lag'monini uyingizda pishiring.",
    description: "Uzun xamir va sershira sabzavotli qayla (waja) uyg'unligi.",
    history: "Ipak Yo'li bo'ylab savdogarlar orqali kirib kelgan, o'zbek bekalari tomonidan mahalliylashtirilgan eng sevimli taomlardan biri.",
    ingredients: ["500g Un", "200ml Suv", "1 dona Tuxum", "400g Mol go'shti", "300g Turp", "200g Bulg'or qalampiri", "Sarimsoq"],
    steps: ["Xamirni mushtlab pishitish", "Ingichka qilib cho'zish", "Qaynoq suvda pishirib olish", "Waja (qayla) tayyorlash", "Xamir ustiga qayla quyish"],
    secrets: ["Xamirni tindirish va yog'lash cho'zilish siri", "Wajani baland olovda qisqa qovuring", "Sarimsoqni oxirida qo'shing"],
    serving: "Chuqur kosada, ko'katlar va lazzat (qalampir) bilan.",
    seoKeywords: ["lag'mon retsepti", "cho'zma lag'mon", "uyg'ur lag'mon", "waja tayyorlash"],
    image: "https://images.unsplash.com/photo-1585032226651-759b368d7246?auto=format&fit=crop&q=80&w=800"
  },
  {
    id: 'manti',
    name: "Tugilgan Manti",
    category: 'Xamir',
    difficulty: "An'anaviy",
    prepTime: '45 min',
    cookTime: '45 min',
    servings: 5,
    price: 38000,
    estimatedDelivery: '45-60 min',
    metaTitle: "Manti Tayyorlash va Sershira Qiyma Sirlari",
    metaDescription: "Bug'da pishiriladigan manti. Yupqa xamir va go'shtli qiyma nisbati. Och Qolma'dan master-klass.",
    description: "Yupqa xamir ichiga yashiringan sershira go'sht va piyoz lazzati.",
    history: "O'rta Osiyo turkiy xalqlari madaniyatining ajralmas qismi. Qadimda har bir qabila o'ziga xos tugish uslubiga ega bo'lgan.",
    ingredients: ["600g Un", "500g Qiyma", "500g Piyoz", "100g Dumba yog'i", "Zira", "Murch"],
    steps: ["Qattiq xamir qorish", "Go'sht va piyozni mayda to'g'rash", "Xamirni yupqa yoyib tugish", "45 min bug'da pishirish"],
    secrets: ["Piyoz qancha ko'p bo'lsa manti shuncha shira beradi", "Qasqon listlarini yaxshilab yog'lang", "Go'shtni pichoqda to'g'rash afzal"],
    serving: "Sariyog' surtib, murch va qatiq bilan.",
    seoKeywords: ["manti tayyorlash", "o'zbek mantisi", "sershira manti", "manti retsepti"],
    image: "https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?auto=format&fit=crop&q=80&w=800"
  },
  {
    id: 'somsa',
    name: "Tandir Somsa",
    category: 'Xamir',
    difficulty: "An'anaviy",
    prepTime: '90 min',
    cookTime: '35 min',
    servings: 10,
    price: 8000,
    estimatedDelivery: '30-45 min',
    metaTitle: "Somsa Qanday Qilinadi? Qarsildoq Varaqi Somsa",
    metaDescription: "Qatlama xamir va sershira qiyma. Tandir va duxovkada somsa pishirishning barcha sirlari.",
    description: "Og'izda eriydigan qarsildoq qatlamlar va sershira go'sht.",
    history: "Somsa - Sharq pishiriqlarining durdonasi. U qadimda savdogarlar va jangchilarning asosiy yo'l ozuqasi bo'lgan.",
    ingredients: ["1000g Un", "250g Sariyog'", "700g Go'sht", "600g Piyoz", "Kunjut", "Tuxum"],
    steps: ["Varaqi xamir tayyorlash", "Xamirni tindirish", "Qiyma tayyorlash", "Tugib 200 gradusda pishirish"],
    secrets: ["Xamir qatlamlari orasiga sariyog'ni sovuq surting", "Piyozni faqat pichoqda to'g'rang", "Ustiga sedan sepishni unutmang"],
    serving: "Pomidorli qayla va achchiq choy bilan.",
    seoKeywords: ["somsa qanday qilinadi", "qatlama somsa", "somsa retsepti", "varaqi somsa"],
    image: "https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&q=80&w=800"
  },
  {
    id: 'shashlik',
    name: "G'ijduvon Kabobi",
    category: 'Kabob',
    difficulty: 'Tez',
    prepTime: '120 min',
    cookTime: '15 min',
    servings: 4,
    price: 18000,
    estimatedDelivery: '30-45 min',
    metaTitle: "Shashlik Marinovka Sirlari va Pishirish | Och Qolma",
    metaDescription: "Go'shtni qanday yumshoq marinovka qilish kerak? Eng yaxshi o'zbek shashlik retseptlari.",
    description: "Ko'mir taftida pishgan xushbo'y va sershira go'sht bo'laklari.",
    history: "Buxoro viloyatining G'ijduvon tumani kabob tayyorlashda jahon bo'yicha etalon hisoblanadi.",
    ingredients: ["1000g Qo'y go'shti", "200g Piyoz", "Zira", "Murch", "Mineral suv"],
    steps: ["Go'shtni bo'laklash", "Ziravorlar bilan marinovka qilish", "2-4 soat tindirish", "Sixga tizing va ko'mirda pishiring"],
    secrets: ["Gazli suv go'shtni yumshatadi", "Kashnich urug'i shashlikka o'zgacha hid beradi", "Sixda go'shtlar orasiga dumba qo'ying"],
    serving: "To'g'ralgan piyoz, uksus va yopgan non bilan.",
    seoKeywords: ["shashlik retsepti", "kabob marinovka", "g'ijduvon kabob", "o'zbek shashligi"],
    image: "https://images.unsplash.com/photo-1635773103713-398d5c953531?auto=format&fit=crop&q=80&w=800"
  },
  {
    id: 'norin',
    name: "Norin Osh",
    category: 'Xamir',
    difficulty: 'Bayramona',
    prepTime: '180 min',
    cookTime: '60 min',
    servings: 8,
    price: 40000,
    estimatedDelivery: '45-70 min',
    metaTitle: "Norin Osh Tayyorlash - Klassik Toshkent Retsepti",
    metaDescription: "Qazili norin retsepti. Xamirni quritish va kesish sirlari. Bayramona o'zbek taomlari.",
    description: "Yupqa kesilgan xamir va sur go'shtning shohona uyg'unligi.",
    history: "Norin asosan Toshkent shahrida sharafli mehmonlar va to'y-hashamlar uchun tayyorlanadigan eng nufuzli taomdir.",
    ingredients: ["1000g Un", "1000g Mol go'shti/Qazi", "Murch", "Yog'", "Piyoz"],
    steps: ["Go'shtni qaynatish", "Xamir yoyib sho'rvada pishirish", "Xamirni yog'lab quritish", "Ingichka somoncha kesish", "Aralashtirish"],
    secrets: ["Xamir va go'sht qancha ingichka kesilsa norin shuncha mazali", "Sho'rvani alohida issiq bering", "Xamirni yog'lashda zig'ir yog'i ishlating"],
    serving: "Sovuq holda, piyoz va bir kosa issiq sho'rva bilan.",
    seoKeywords: ["norin osh", "norin retsepti", "toshkent norini", "qazili norin"],
    image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&q=80&w=800"
  },
  {
    id: 'chuchvara',
    name: "Kichik Chuchvara",
    category: 'Suyuq',
    difficulty: 'Tez',
    prepTime: '40 min',
    cookTime: '20 min',
    servings: 4,
    price: 28000,
    estimatedDelivery: '30-45 min',
    metaTitle: "Chuchvara Retsepti - Mayda va Mazali Barak",
    metaDescription: "Mayda chuchvara tugish va sho'rva tayyorlash. Uy sharoitida mazali tushlik tayyorlang.",
    description: "Mittigina tugilgan xamirchalar, sershira sho'rva bilan.",
    history: "Chuchvara oilaviy birdamlik ramzi - odatda hamma yig'ilib birgalikda tugadi.",
    ingredients: ["500g Un", "400g Qiyma", "2 dona Piyoz", "Pomidor", "Kashnich"],
    steps: ["Xamir yoyish", "Kichik kvadratlarga bo'lish", "Tugish", "Sho'rvada pishirish"],
    secrets: ["Chuchvara qancha mayda bo'lsa oshpaz shuncha epchil sanaladi", "Rayhon qo'shish xushbo'ylik beradi", "Qaynoq suvga bir dona piyoz butun soling"],
    serving: "Kosa bilan, ustiga qaymoq va ko'katlar solib.",
    seoKeywords: ["chuchvara retsepti", "mayda chuchvara", "suyuq taomlar", "o'zbek barak"],
    image: "https://images.unsplash.com/photo-1547592110-823d6330005d?auto=format&fit=crop&q=80&w=800"
  },
  {
    id: 'qovurma',
    name: "Qovurma Lag'mon (Quruq)",
    category: 'Asosiy',
    difficulty: 'Tez',
    prepTime: '30 min',
    cookTime: '25 min',
    servings: 2,
    price: 35000,
    estimatedDelivery: '35-50 min',
    metaTitle: "Qovurma Lag'mon Retsepti - Tezkor va To'yimli",
    metaDescription: "Go'sht va sabzavotlar bilan qovurilgan lag'mon. Erkaklar sevib iste'mol qiladigan taom retsepti.",
    description: "Jizillab qovurilgan go'sht va xamirning quruqroq, xushxo'r varianti.",
    history: "Cho'ponlar va jangchilarning ochiq olovda tez pishiradigan to'yimli taomi bo'lgan.",
    ingredients: ["500g Lag'mon xamiri", "300g Go'sht", "Kartoshka", "Piyoz", "Sarimsoq"],
    steps: ["Go'shtni qizarguncha qovurish", "Sabzavotlarni qo'shish", "Xamirni alohida pishirib qovurish", "Ziravorlar bilan dimlash"],
    secrets: ["Sabzavotlar butun qolishi kerak (al-dente)", "Zira va murch nisbati muhim", "Sarimsoqni yog'da biroz qovurish xushbo'ylik beradi"],
    serving: "Laganda, ustiga qovurilgan tuxum qo'yish mumkin.",
    seoKeywords: ["qovurma lag'mon", "qovurma retsepti", "tezkor tushlik", "milliy qovurma"],
    image: "https://images.unsplash.com/photo-1603048588665-791ca8aea617?auto=format&fit=crop&q=80&w=800"
  }
];
